language: python

#List the versions of python to test against
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

branches:
  only:
    - master

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 pylint sphinx --use-mirrors
  - pip intsall -e .

script:
  # Validate PEP8 compliance
  - pep8 -r  --statistics  --count pytvdbapi/

  # Validate PyLint compliance
  - pylint --rcfile=pylint.cfg pytvdbapi

  # Test the examples in the README file
  - python -m doctest -v README.rst

  # Run all unittests and doctests
  - python -m setup.py test

  # Test that the documentation is working
  - cd docs/source/
  - sphinx-build -W -b html -d /tmp/doctrees .  /tmp/html
  - sphinx-build -W -b linkcheck -d /tmp/doctrees .  /tmp/linkcheck

notifications:
  email:
    - develop@bjornlarsson.net